apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: alien
  name: alien-pods
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","pods/log"]
  verbs: ["get", "watch", "list"]