apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-multyt-dep
  labels:
    app: busym-d
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busym-d
  template:
    metadata:
      labels:
        app: busym-d
    spec:
      containers:
      - name: busybox
        image: busybox
        command: 
        args:
          - "/bin/sh"
          - "-c"
          # - "mkdir /mnt/busy_d"
          - "while true;do date +%H:%M:%S >> /tmp/multy/date.d;sleep 5;done"
          # - "5"
          # - "touch /mnt/busy_d/date.d"
          # - "echo date +%H:%M:%S >> /mnt/busy_d/date.d'"
        volumeMounts:
          - mountPath: "/tmp/multy"
            name: local-volume
#     
      - name: network-multitool
        image: wbitt/network-multitool
        # env:
        # - name: HTTP_PORT
        #   value: "1180"
        # - name: HTTPS_PORT
        #   value: "11443"
        ports:
        - containerPort: 1180
          name: http-port
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
        volumeMounts:
          - mountPath: "/tmp/multy"
            name: local-volume
#              
      volumes:
        - name: local-volume
          emptyDir: {}
        - name: local-volume1
          emptyDir: {}