apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: e2e
  name: hello-world
#  namespace: default
spec:
  containers:
  - name: e2e
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080
    #   name: web
    #   protocol: TCP
    # imagePullPolicy: IfNotPresent