apiVersion: v1
kind: Service
metadata:
  name: netology-svc
#  namespace: default
spec:
  selector: 
    app: e2e
  ports:
  - name: service-port
    #targetPort: echoserver-web
    port: 8080
    #protocol: TCP
    # imagePullPolicy: IfNotPresent