---
# Source: sky-chart-0/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-sky-chart-0
  labels:
    helm.sh/chart: sky-chart-0-0.1.0
    app.kubernetes.io/name: sky-chart-0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.17.6"
    app.kubernetes.io/managed-by: Helm
---
# Source: sky-chart-0/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-sky-chart-0
  labels:
    helm.sh/chart: sky-chart-0-0.1.0
    app.kubernetes.io/name: sky-chart-0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.17.6"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: sky-chart-0
    app.kubernetes.io/instance: release-name
---
# Source: sky-chart-0/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-sky-chart-0
  labels:
    helm.sh/chart: sky-chart-0-0.1.0
    app.kubernetes.io/name: sky-chart-0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.17.6"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: sky-chart-0
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sky-chart-0
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-sky-chart-0
      securityContext:
        {}
      containers:
        - name: sky-chart-0
          securityContext:
            {}
          image: "nginx:1.17.6"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
