apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-1
spec:
  replicas: 4
  
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
      
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
      initContainers:
        - name: delay
          image:  busybox
          command: ['sleep','40']

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: netology-svc-nginx
# #  namespace: default
# spec:
#   selector:
#     app: nginx-1
#   ports:
#   - name: service-port
#     port: 88