apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multy-deployment
  labels:
    app: nginx-multy
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: nginx-multy
  template:
    metadata:
      labels:
        app: nginx-multy
      
    spec:
      # hostNetwork: true
      # tolerations:
      # - operator: Exists
      #   effect: NoSchedule
      # volumes:
      # - name: n-m  
      #   emptyDir: {}
      containers:
      - name: nginx
        image: nginx:1.14.2
        # volumeMounts:
        # - name: n-m
        #   mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
          # port: 80
          name: nginx-port
       # imagePullPolicy: Never
#  
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 8080
          name: http-port
          # port: 9002
        - containerPort: 11443
          name: https-port
          # port: 12443
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
        # securityContext:
        #   runAsUser: 0
        #   capabilities:
        #     add: ["NET_ADMIN"]

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc1
#  namespace: default
spec:
  selector:
    app: nginx-multy
  ports:
    - name: nginx-port
      targetPort: 80
      port: 9001
    - name: http-port
      targetPort: 8080
      port: 9002   
    #protocol: TCP
    # imagePullPolicy: IfNotPresent

