apiVersion: v1
kind: Service
metadata:
  name: netology-svc2
#  namespace: default
spec:
  selector:
    app: nginx-multy
  ports:
    - name: nginx-port
      targetPort: 80
      port: 9001
      nodePort: 31001
    - name: http-port
      targetPort: 8080
      port: 9002   
      nodePort: 31002
  type: NodePort
        
    #protocol: TCP
    # imagePullPolicy: IfNotPresent
