apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  # namespace: ingress
  labels:
    app: nginxd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxd
  template:
    metadata:
      labels:
        app: nginxd
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        #- port: 8080
          name: nginx-port

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  # namespace: ingress
spec:
  selector:
    app: nginxd
  ports:
    - name: nginx-port
      targetPort: 80
      port: 9001
  #type: NodePort
  type: ClusterIP
  

# ---
# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: nginx-config
#   #namespace: nginx-ingress
# data:
#   proxy-connect-timeout: "10s"
#   proxy-read-timeout: "10s"
#   client-max-body-size: "2m"
#   external-status-address: "192.168.1.4"