apiVersion: apps/v1
kind: Deployment
metadata:
  name: multy-dep
  labels:
    app: multyd
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: multyd
  template:
    metadata:
      labels:
        app: multyd
      
    spec:
      # hostNetwork: true
      # tolerations:
      # - operator: Exists
      #   effect: NoSchedule
      # volumes:
      # - name: n-m  
      #   emptyDir: {}
      containers:
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http-port
        - containerPort: 11443
          name: https-port
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
        # securityContext:
        #   runAsUser: 0
        #   capabilities:
        #     add: ["NET_ADMIN"]

---
apiVersion: v1
kind: Service
metadata:
  name: multy-svc
spec:
  selector:
    app: multyd
  ports:
    - name: http-port
      targetPort: 1180
      port: 9002     
    #protocol: TCP
  #type: NodePort 
  type: ClusterIP
