apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-multy
  #namespace: dev
spec:
  rules:
  - host:  
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              # name: nginx-port
              number: 9001
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: multy-svc
            port:
              #name: http-port
              number: 9002
