# sc-nfs.yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-mn1
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.3
  share: /srv/nfs/
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1        

# pvc-nfs.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: nfs-csi-mn1
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100M