apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nm
spec:
  capacity:
    storage: 100M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "" #slow
  hostPath:
    path: /tmp/svf
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nm
spec:
  storageClassName: ""
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100M